name: "\U0001F41B Bug Report"
description: bug에 대해서 설명해주세요
body:
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: system info를 먼저 공유해주세요.
      placeholder: branch name, project version, python version
    validations:
      required: true

  - type: textarea
    id: who-can-help
    attributes:
      label: Who can help?
      description: |
        버그 코드를 맡거나 원하시는 팀원이 있다면 @로 태그를 걸어주세요.
        
      placeholder: "@Username ..."

  # - type: checkboxes
  #   id: information-scripts-examples
  #   attributes:
  #     label: Information
  #     description: '쓸때 생긴 문제에 대해 체크해주세요.'
  #     options:
  #       - label: "The official example scripts"
  #       - label: ""

  # - type: checkboxes
  #   id: information-tasks
  #   attributes:
  #     label: Tasks
  #     description: "The tasks I am working on are:"
  #     options:
  #       - label: "An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)"
  #       - label: "My own task or dataset (give details below)"

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        버그가 있는 코드와 error message, stack traces 같은 것들을 올려주세요.
        해당 링크에 들어가시면 스크린샷 대신에 코드를 복사하는 방법이 있습니다.
        https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting

      placeholder: |
        문제 재현을 위한 step을 자세하게 설명해주세요.
          1.
          2.
          3.
          

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: 예상 결과 및 원하는 결과
      description: "예상결과나 원하는 결과를 명확하고 자세히 적어주세요."